import Navbar from "../components/layout/Navbar/Navbar";

function HomePage() {
  return (
    <div>
      <Navbar />
      <main>
        <div style={{ padding: '2rem' }}>
          <h1>Pure Spike Studio</h1>
          <p>HomePage placeholder – Impulse Generator coming soon.</p>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corrupti totam tempora perspiciatis reiciendis voluptatem, odit, expedita laboriosam incidunt accusantium numquam amet quaerat vel adipisci est dolore ducimus ipsam maxime fuga?
          Hic, magni, molestiae ex perferendis perspiciatis ducimus atque eum minima quaerat quisquam sunt ipsam placeat cum blanditiis facere. Consequatur animi qui blanditiis? Obcaecati fuga praesentium dolor nulla in! A, cum?
          Sequi porro praesentium sunt vitae obcaecati, dolore officiis voluptas. Libero mollitia a ad quidem molestiae distinctio ipsa perferendis porro temporibus illum consequuntur eos modi assumenda atque consectetur alias, cupiditate sunt.
          Aperiam praesentium illo sint nulla sequi atque ex suscipit debitis dolorem eius perspiciatis natus nemo doloremque deserunt illum temporibus ea ut magni dolor eum iure, amet officia? Dignissimos, delectus odio!
          Corrupti asperiores architecto nihil ratione repellat, incidunt laborum aliquam sunt inventore tempora sit quos quia debitis unde consectetur ipsa? Nesciunt qui est eveniet doloribus provident reprehenderit similique natus inventore voluptatum.
          Quae nemo a rerum quaerat aliquid expedita tenetur optio deserunt? Beatae magnam facilis cum itaque temporibus, earum eligendi, nulla ut quas vitae quae sit tempore quaerat similique repellat cumque iste.
          Animi excepturi est iste. Eos nostrum fugiat consequatur, porro vel sapiente! Laudantium corrupti ratione obcaecati officia sunt, quasi nam error quod nesciunt? Aperiam, quia quibusdam quo cumque amet ea vero?
          Numquam ad tempora, cumque blanditiis recusandae accusamus facere eligendi nobis. Voluptate, sequi. Quibusdam culpa sit nostrum, molestiae saepe, optio laboriosam dolor vitae libero fuga illo eveniet illum quasi commodi consequuntur?
          Possimus dolore sint tempora, voluptatem corrupti illo reiciendis perspiciatis rem fuga error minima iusto vero distinctio veniam numquam rerum vitae! Blanditiis earum ex ducimus, autem commodi veniam iusto nihil minus.
          Ducimus impedit modi facilis nostrum, architecto sed vero tempore veniam. Quisquam illum neque cum, officiis molestias perspiciatis necessitatibus omnis sequi voluptates, odit laborum, optio recusandae. Repellendus dolorum excepturi eum perspiciatis.
          Nesciunt ullam repellendus, architecto dolore nostrum natus inventore beatae expedita repellat qui quas ipsum at corporis ducimus libero recusandae voluptatem. Assumenda adipisci dolores error esse maiores, accusantium accusamus explicabo amet!
          Quasi deserunt qui aliquid vitae eius tempora ut sint non, ipsum quidem. Animi tempore dolorem numquam assumenda repellendus explicabo quis, qui iste asperiores nisi dolore, eius ipsa et voluptas. Rerum!
          Unde vitae blanditiis, animi saepe, adipisci reprehenderit consequatur earum nesciunt voluptatum delectus minima veritatis debitis odit neque voluptatem. Mollitia iste porro perferendis dolorum omnis quasi, quia consequatur est facilis accusamus.
          Aspernatur similique inventore autem illum hic deleniti nihil, quasi repudiandae quia quaerat, quam voluptates impedit placeat odio voluptatum quos debitis necessitatibus voluptas eos laudantium? Corrupti ipsam assumenda temporibus recusandae hic!
          Quia corporis sed vel laborum est! Eveniet non reiciendis mollitia error neque laboriosam facere veniam. Delectus autem excepturi consequuntur rem provident saepe commodi, deserunt tempora quo veniam, quia perspiciatis temporibus!
          Adipisci consequatur amet delectus eveniet eaque assumenda inventore laboriosam placeat unde ea officiis, nulla nihil maxime odio modi. Earum repudiandae optio dicta quidem impedit atque omnis nam iste provident consectetur!
          Facilis est dolores inventore, accusantium autem deleniti voluptates sunt vitae! Suscipit asperiores aperiam nostrum, illo, aut aspernatur ratione, atque iusto veniam nobis provident nulla at aliquid molestiae accusantium iure! Eligendi?
          Earum placeat, laboriosam illum similique ut error dicta nobis. Voluptatem dolore culpa officia cumque velit laborum. Magnam architecto, facilis ipsam, eius voluptas expedita repellendus quidem reiciendis voluptates labore in aliquam!
          Odio est itaque, obcaecati saepe optio magni reprehenderit quis sunt quidem hic vitae qui dicta quod perferendis explicabo eius ab impedit ullam. Excepturi, impedit atque temporibus assumenda necessitatibus inventore mollitia.
          Reiciendis commodi officia molestiae fugiat? Inventore iste sint ad debitis neque repudiandae assumenda, non temporibus culpa esse, accusamus illo at vero. Vero consequatur sequi minus perferendis magnam iste, incidunt magni!
          Veniam delectus tempora illo, hic, voluptate quisquam, ratione amet quod dignissimos possimus dolorum? Dolores, soluta, aperiam, dolorum iste ex quam sequi tenetur sunt provident ipsa totam tempora excepturi necessitatibus animi.
          Illo, ipsam dolores? Magnam, sapiente libero nisi minus dolores repudiandae qui natus! Sint odit autem eum accusantium modi. Nobis a ut excepturi assumenda suscipit minus non neque esse, dignissimos eum?
          Beatae tempore nobis atque pariatur. Quasi quis rerum facilis repellat tenetur reiciendis facere! Sapiente, animi voluptatibus! Voluptas dolorum dolor placeat exercitationem maiores. Facere quae dolores, perspiciatis quod qui omnis tempora!
          Quod aliquid veritatis possimus eum, velit ut ea eius illo quasi. Excepturi natus, exercitationem expedita reiciendis earum at minus mollitia, quos porro, repellat esse laborum dolore! Quae quas quo dolorem.
          Placeat recusandae deleniti inventore repellat quasi aliquam magnam fugiat harum, molestias pariatur repellendus, labore est modi quod suscipit voluptatem impedit sed eveniet quo dolores adipisci? Nesciunt impedit earum corrupti illum!
          Doloremque dolores quam eveniet in impedit omnis illum, harum tempore atque, cumque quo natus similique repudiandae sequi illo magnam labore quae. Molestias obcaecati quo suscipit in consequuntur cupiditate delectus porro.
          Vitae, a, mollitia itaque numquam culpa debitis expedita atque sequi molestiae corrupti incidunt cumque. Architecto ducimus nesciunt eligendi iste nulla aspernatur, molestiae aut necessitatibus, repellendus sequi perferendis quis eveniet vero?
          Omnis, eos sint. Nemo sit numquam deserunt, mollitia dolores dolor at est ipsum animi commodi tempora minima quasi doloribus ad ea officiis, error fugiat eligendi consequatur esse sint ipsa in.
          Magnam sint, odit quibusdam corporis voluptatum eos voluptas cupiditate deserunt deleniti omnis quae, corrupti libero voluptate beatae qui praesentium tempore minus explicabo repudiandae. Facere officiis quis eius numquam dolore nam.
          Maiores rem ullam consectetur fugit. Nesciunt quos magni aperiam, facilis rem optio praesentium qui, ducimus itaque adipisci, at eum consequatur voluptatem laudantium amet temporibus doloremque eligendi et totam assumenda quibusdam.
          Sequi consequuntur repellendus voluptatem cumque porro, soluta tenetur beatae neque in totam impedit nisi mollitia nobis magni velit pariatur eius tempora assumenda, qui eligendi nesciunt eos. Ex ducimus placeat perspiciatis.
          Fugiat ut magni consectetur, alias explicabo ratione adipisci. Consequuntur illum neque inventore sapiente qui quasi iure! Corporis voluptatum at, reiciendis provident accusamus nulla repellendus. Sed nesciunt et saepe ipsa totam?
          Non sit id totam corrupti? Assumenda non obcaecati rem facilis inventore omnis odio reprehenderit magni recusandae dolores eveniet ea quisquam, ratione voluptas exercitationem perspiciatis aspernatur vitae expedita possimus velit impedit.
          Reprehenderit architecto adipisci porro hic sit mollitia nam, maiores commodi exercitationem facilis nemo consectetur, ab, nostrum magni error debitis aliquid quidem corrupti itaque laborum deleniti consequatur voluptatem tenetur? Hic, possimus?
          Voluptatum quaerat quibusdam exercitationem adipisci pariatur error perspiciatis sint facere inventore incidunt saepe, a excepturi eum at veritatis sed ducimus! Rem nostrum dolorem aut ab non neque vitae culpa aperiam?
          Excepturi, fuga facere, atque eius adipisci corporis tempore maiores temporibus rerum porro facilis voluptatum provident ratione ipsam nihil, ut sed illo! Itaque magni ullam odit animi id vel iure dolor!
          Sequi porro animi iste suscipit aspernatur maiores laudantium velit sed, officia non at ad. Fuga eos, at perspiciatis tenetur eum natus, sit obcaecati, excepturi est consequuntur qui commodi! Hic, fuga?
          Provident quam dolores aliquid ea rem repellendus ducimus. In laudantium ipsa, quis ipsum ex amet eum ratione, possimus pariatur nostrum quibusdam dolor porro molestiae tempora atque eos laborum hic autem.
          Distinctio optio, quibusdam reiciendis eum laboriosam explicabo praesentium, cum deserunt beatae pariatur dolorem nesciunt. Laboriosam illo exercitationem quibusdam officiis tempore aut soluta suscipit, corrupti consectetur culpa dolores impedit possimus assumenda?
          Asperiores aliquam ipsa et aliquid voluptates quidem iusto. Odit quidem, voluptatem natus inventore, rem reprehenderit laboriosam obcaecati excepturi aut numquam et eligendi dolor libero amet ipsum nemo, similique distinctio omnis.
          At dicta ut debitis, provident beatae suscipit soluta amet porro iste pariatur tempora blanditiis sequi voluptatem. Facere, ducimus, facilis cupiditate asperiores tempora nam totam pariatur delectus debitis assumenda ex velit!
          Repudiandae reprehenderit quaerat modi cumque ratione at libero eveniet ipsum inventore facere aperiam, ullam quod blanditiis praesentium dolores perferendis, minima accusamus molestias a deleniti? Maiores suscipit at molestiae earum ab.
          A et enim praesentium, voluptatum quisquam illum sed explicabo itaque ex aperiam illo tempore odit molestias facilis ab laboriosam dolore aliquid perferendis libero animi dolor voluptatem iusto ipsa! Culpa, nemo?
          Quae suscipit veritatis, iste id officia impedit. Similique incidunt ut quibusdam, veniam, ex dolor at obcaecati, corrupti quisquam alias itaque veritatis provident. Maiores eaque pariatur optio consectetur atque odio doloribus.
          Necessitatibus modi repellat libero blanditiis, vitae repellendus at officiis? Quam, beatae porro! Laudantium minima quam voluptatum quidem ipsum, nihil delectus eos quod atque laborum obcaecati aliquid eaque mollitia officia a!
          Sapiente rerum officiis, autem quibusdam sint vitae nesciunt, quod voluptatibus repudiandae nam corrupti excepturi quia hic quis similique cumque dolorum! Saepe, exercitationem deserunt! Similique, explicabo quia veniam repellendus sequi unde!
          Recusandae placeat porro impedit veniam, consequatur accusantium itaque et, dolorem, possimus in cumque obcaecati suscipit maiores quae tempora? Soluta, animi blanditiis nisi ipsa architecto repellendus at commodi distinctio illum magnam.
          Adipisci optio doloribus libero at iusto alias ab ratione, vitae porro aut sequi explicabo cumque dicta corrupti suscipit beatae, temporibus cum, tempore facere aliquam! Labore, laboriosam adipisci. Totam, autem explicabo!
          Incidunt fuga quia at impedit consequuntur suscipit eos! Ab, quibusdam praesentium incidunt quisquam labore eos est omnis sed rerum enim illo, repellendus et laudantium quo nam modi impedit eaque sapiente?
          Impedit pariatur praesentium culpa quam perferendis. Sequi repellat facilis voluptas recusandae dolorum ipsam, eveniet tenetur earum quas quam maiores provident assumenda autem odit, quo, praesentium vero sed pariatur mollitia fugiat?
          Minus veniam eum voluptatum, unde earum iusto, ratione debitis cupiditate dolores dignissimos amet temporibus. Alias id ipsa laudantium amet nemo animi quas nisi illo quisquam enim. Nulla et doloribus minus!
          Doloribus ea aperiam iure eum molestiae velit, deleniti quos eveniet tenetur maiores quae natus at animi earum, quas inventore magni in. Sit minima nam ducimus dignissimos ex et voluptatem placeat!
          Commodi repellat illum vitae, maxime voluptas impedit inventore ex fugiat voluptatibus, ratione, culpa blanditiis aspernatur quo unde eaque odio eveniet perferendis. Perferendis autem dicta rerum libero mollitia quia nulla asperiores?
          Tempore perspiciatis eum magni, voluptatibus sunt maxime nemo! Quo placeat perspiciatis nemo a ab. Quidem, perspiciatis corrupti unde sunt nihil eius voluptate atque facere, quaerat laborum, obcaecati quisquam fugit fugiat!
          Nihil, quasi. Vitae maxime explicabo dolorem, facilis ex asperiores culpa. Laborum maxime quibusdam natus eos in, exercitationem ipsum ut omnis vel voluptatum dignissimos reprehenderit, officia tempore dolorem hic ducimus itaque.
          Quia eum rerum qui, corrupti est deleniti blanditiis, reprehenderit debitis odit quibusdam incidunt temporibus illo suscipit odio labore nisi? Quaerat laboriosam accusamus illo tempore repellat omnis odit sapiente inventore perferendis.
          Cum quia doloremque cupiditate reprehenderit commodi dolor repellat ipsum tenetur, iure veritatis ad odit praesentium omnis! Ad autem accusamus perferendis. Dignissimos optio quam veniam sunt rem? Nobis optio eius obcaecati.
          Exercitationem, corrupti nam vel pariatur recusandae quia, molestiae alias omnis incidunt iure atque dicta laudantium labore deserunt expedita similique cupiditate? Magni saepe velit sit suscipit officiis unde molestiae voluptate porro.
          At doloribus impedit exercitationem repellat. Enim, eligendi suscipit animi, ex odit minima delectus quos ratione exercitationem earum sequi doloribus iste. Quaerat quisquam, quis animi hic in odit sapiente quos. Aliquid!
          Vero fugiat nemo itaque! Officia autem eius blanditiis aut dolorum libero, et nisi nihil quia, impedit deleniti perspiciatis laudantium repellendus voluptates aliquid quisquam recusandae porro eaque labore sit repellat! Voluptates!
          Delectus debitis, est iste ipsa alias aliquid atque earum dignissimos esse, maiores voluptate culpa, mollitia minima. Nesciunt dolores, ex temporibus, iste in aperiam magni eveniet rem praesentium cumque sit quisquam.
          Perferendis quia corrupti et blanditiis, voluptatem rem delectus dolore. Quaerat nemo vero veniam, suscipit exercitationem animi molestiae illum minima accusantium illo aliquam hic adipisci necessitatibus placeat, enim eius sapiente. Quae.
          Cupiditate maiores voluptatem, adipisci explicabo iure reprehenderit voluptas voluptatibus rerum eligendi nemo iste minima provident molestias quo laboriosam quae maxime aut quam? Dolor quod illo illum accusamus. Explicabo, officiis ex!
          Nihil, corrupti eveniet qui laborum reprehenderit soluta consectetur cum, tempora non corporis consequuntur dolor cumque voluptate sed laudantium quisquam odio quidem mollitia esse commodi sit. Fuga unde harum alias quisquam.
          Officiis fugiat corporis officia. Eligendi provident voluptatem, repellendus mollitia culpa cumque vel ratione voluptate nemo doloribus maxime consequuntur. Aut ipsa harum suscipit, perferendis nostrum rerum veniam quas eligendi nam placeat?
          Suscipit consectetur modi doloribus a minus quia corporis quas blanditiis hic id distinctio, molestias qui vitae omnis itaque pariatur nostrum velit commodi fugiat nesciunt. Pariatur error aperiam reiciendis ipsam odit.
          Est eius deserunt quae molestiae maiores voluptate, nobis distinctio mollitia officiis accusantium temporibus esse repellendus accusamus sunt odit doloremque, unde illum sit. Aliquid tenetur exercitationem ab sint. Corporis, non tempora?
          Est, suscipit. Adipisci dignissimos aut accusamus animi, numquam sunt illum maiores nulla deleniti perferendis maxime quasi cupiditate perspiciatis iure, sapiente eveniet qui asperiores vel voluptate quo sit! Expedita, repellat ratione!
          Pariatur, quidem. Incidunt in accusantium esse consectetur accusamus quisquam atque sunt perferendis deserunt non, alias odit blanditiis totam eum suscipit optio nam sequi porro tenetur molestiae quia. Odit, aspernatur optio?
          Modi quae eos sint, tenetur cupiditate, ducimus quaerat at ad dolores sed consequatur odit. Esse nostrum aliquid architecto necessitatibus, porro quo qui vero animi voluptatibus ipsum accusamus mollitia dolores nisi.
          Temporibus facilis expedita inventore iure laudantium odit beatae saepe vitae quisquam officiis eligendi, velit, maiores ducimus animi reiciendis odio nemo culpa! Excepturi consectetur assumenda cum, rem accusantium rerum. Magnam, deleniti?
          Aperiam odit maxime quasi! Qui ipsam debitis voluptatibus labore quo velit sequi. Illum maiores dolorem necessitatibus, ipsa voluptas dolore tempora quisquam fugit corrupti perferendis perspiciatis odio autem quibusdam et amet.
          Quisquam ab repellendus iusto sapiente omnis est odio tempora suscipit eos. Nihil quo sequi culpa quasi, quas quis modi animi officiis corrupti molestias voluptas assumenda tempore ad repellat explicabo numquam.
          Eaque, laudantium omnis vitae dolorem aliquid amet in nemo facere nesciunt accusamus itaque ipsum doloribus aut repellendus nobis reprehenderit iure est excepturi, rem quam libero quas, suscipit quasi id. Quod.
          Earum, hic. Ducimus nihil earum facilis quae consequatur blanditiis vel perferendis dolorem quisquam eos, nulla ex reprehenderit voluptatum aperiam alias? Tempore iusto architecto dolorum cum consectetur voluptates iste magni aspernatur.
          Excepturi quisquam aliquid, itaque totam autem et commodi fugiat nisi velit consectetur inventore similique aut odit dolore, incidunt quibusdam. Laborum tempore, repellendus dolore corporis voluptate assumenda deleniti unde delectus pariatur!
          Nam culpa eligendi et consectetur dolorem reiciendis! Adipisci voluptas alias, tempora nemo beatae at? Possimus repellat veritatis, facilis voluptate ipsum tempore animi quidem nam harum! Et dolorem perferendis tempore optio!
          Facere eligendi nostrum alias iure sapiente ea a, omnis ratione nemo eum amet et quibusdam qui atque aperiam minus natus! Quia quis fugiat tempore aspernatur, perspiciatis dicta aliquid a eos.
          Quibusdam beatae quos laborum molestiae animi fuga, necessitatibus officiis, ad eum reiciendis corrupti aliquid velit nulla debitis exercitationem? Consequatur incidunt deleniti laudantium dignissimos cupiditate repellendus harum sapiente. Veniam, aspernatur ad?
          Quam odio porro totam dolores dolorem illum sint fugit magni ab qui consequatur maxime est illo a, hic, sapiente minus facere delectus possimus. In atque vitae exercitationem, aliquam dicta dignissimos?
          Debitis sint harum cupiditate autem error iure consequuntur impedit in omnis, libero laborum eaque! Adipisci laboriosam suscipit, sapiente neque quis incidunt labore, possimus assumenda dicta commodi, repellat perspiciatis. Eaque, nesciunt?
          Cumque fugit temporibus iusto quae ex similique, deleniti doloribus sed quod sunt. Quisquam fugiat laboriosam ratione, numquam illo, modi reiciendis corporis quis quidem nam consequatur quae quos dolor, eligendi similique!
          Deleniti repudiandae voluptates tempora libero, hic, nesciunt autem ex dolorum molestias quasi doloremque sequi sed consectetur fugit eligendi assumenda debitis, vero aspernatur! Sed laborum velit vero atque repellat possimus officiis.
          Odio quis vero quae dolorum quaerat reprehenderit quo, quod asperiores ab sunt nobis doloribus. Corrupti omnis provident iure reiciendis? Commodi possimus dolores molestias maiores nesciunt, facilis voluptates consectetur nobis provident!
          Ea, itaque cupiditate vel earum magni hic voluptatum ipsam doloribus voluptatibus odit placeat eveniet, dicta nam corporis, eligendi alias officia recusandae impedit in quaerat architecto! Iusto excepturi tempore nihil architecto.
          Veniam impedit reiciendis quae quibusdam dicta nobis accusantium eligendi inventore quidem. Quam numquam quo dolorum blanditiis excepturi, quasi fugit facere consequatur soluta dolore nam facilis inventore illo iure, suscipit repellendus!
          Sed ab, nam voluptates cum veritatis, quod quidem tempore, sapiente laborum libero natus? Voluptatum quae soluta magni, vero ullam temporibus reprehenderit fugiat nesciunt? Nisi unde dolore quis cum ea veritatis?
          Omnis enim, laborum quas facilis dicta suscipit amet doloribus repellat in inventore accusantium. Reiciendis aut nostrum perspiciatis quia deleniti magni, magnam obcaecati molestias sequi ad cupiditate, voluptas, eum accusamus. Sint?
          Veniam, nihil sed! Itaque tempore fugit minus earum ea sint ut! Exercitationem aut doloribus eos veritatis blanditiis facere debitis aperiam nesciunt unde odio nostrum repellendus perferendis placeat fugit, sint dolor?
          Molestiae inventore deleniti culpa, eos tenetur error sapiente temporibus repellendus reprehenderit dolor veniam ullam consequuntur nulla sint esse consequatur. Assumenda cupiditate natus odio dolor non illo earum neque nemo molestias.
          Beatae saepe modi fugit, natus, fuga omnis repellendus nesciunt et reiciendis maiores a, dolorum aliquid fugiat autem eligendi optio! Harum minima officia expedita ipsum doloribus officiis dolorem facere pariatur voluptas.
          Dolorum adipisci reiciendis est aut molestiae magni assumenda provident vel, facere quia numquam impedit neque ipsa animi. Beatae maiores facere ut, aliquam cum, voluptatem, vitae eveniet sit laborum suscipit dicta?
          Omnis fugit nostrum itaque nisi! Nam harum eligendi sed nesciunt corrupti voluptatum modi ut recusandae suscipit et accusantium dolore aliquid doloremque alias id, quo reprehenderit. Cum quae nostrum facilis enim.
          Beatae aperiam quam natus eius totam officia accusantium, facere labore eum, neque culpa inventore, aliquam eligendi laboriosam debitis veritatis quia. Dicta ipsum eveniet dolores necessitatibus aliquam cum corrupti laudantium reiciendis!
          Illo quae, sequi consectetur incidunt culpa ullam facere, esse suscipit quia, ab vero similique cumque doloremque? Repellendus harum quo suscipit. Reprehenderit est fugit nam doloremque nostrum quae fugiat delectus itaque.
          Incidunt, dicta. Aperiam obcaecati beatae officia tenetur magnam voluptas iste nobis culpa consequuntur excepturi assumenda ipsam asperiores, necessitatibus similique distinctio consequatur sit sapiente, illum fugiat laboriosam quisquam numquam rem esse.
          Dolorum cum impedit laborum rerum, vero recusandae eius ratione, saepe quibusdam error possimus assumenda amet consectetur laudantium! Unde accusantium fugit, natus vero repudiandae sed optio perspiciatis fuga sequi, quaerat dolorem?
          Illum, nihil cum! In quidem, eveniet soluta voluptatibus obcaecati distinctio repudiandae eius recusandae inventore enim eos exercitationem itaque magnam sit pariatur. Quibusdam ab ipsam et laudantium dicta temporibus, obcaecati ea!
          Tempore, aut minima culpa quia hic commodi fugiat quis dignissimos, explicabo velit nam fugit repellendus reiciendis non voluptatem recusandae dicta fuga nulla voluptate illum deserunt. Natus laboriosam reprehenderit possimus. Iusto.
          Saepe ratione magnam placeat! Fugiat architecto itaque, vel maxime delectus debitis id! Voluptatibus, soluta ipsa. Dolorum ducimus ratione impedit corporis minima. Earum animi natus voluptatem fuga accusantium corporis? Labore, sint?</p>
        </div>
      </main>
    </div>
  );
}

export default HomePage;